[Update] Newtonsoft.Json to 13.0.1
RHEAGROUP/COMET-SDK-Community-Edition pull request #196
Opened 2021-08-02 07:32 UTC by samatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-SDK-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Update a number of dependencies:

- Newtonsoft.Json to 13.0.1
- DotNetZip to 1.14.0
- NLog to 4.7.10

2021-08-02 07:39 UTC, lxatrhea approved these changes

2021-08-02 08:31 UTC, SimonWoodRhea requested changes
An exception was thrown from the bootstrapper when running IME. 
I had to consolidate the System.Threading.Tasks.Extensions across all projects. I think it was CDP4IME-CE with a lower version.

2021-08-02 08:43 UTC, SimonWoodRhea approved these changes

2021-08-02 15:16 UTC, alexatrhea approved these changes

2021-08-05 13:35 UTC, samatrhea commented
merged in commit 788282615efc976da917c8e02d099dff2a996521

2021-08-05 13:35 UTC, closed without merging