[Fix] Deserialize ValueSets ;Fixes #205
RHEAGROUP/COMET-SDK-Community-Edition pull request #206
Opened 2021-09-28 12:55 UTC by lxatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-SDK-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Fixes a bug on deserializing ValueSets that contain specific escape characters that aren't used as escape characters.

2021-09-29 07:06 UTC, samatrhea requested changes

2021-09-29 07:06 UTC, samatrhea commented on CDP4Common/CDP4Common.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
a dependency on `Newtonsoft.Json` in CDP4Common needs to be avoided.

2021-09-29 14:31 UTC, samatrhea requested changes

2021-09-29 14:31 UTC, samatrhea commented on CDP4JsonSerializer/Helper/SerializerHelper.cs
> +        public static string ToJsonString(ValueArray<string> valueArray)
we could make this an extension method: `public static string ToJsonString(this ValueArray<string> valueArray)`

2021-09-29 14:57 UTC, alexatrhea approved these changes

2021-09-29 14:59 UTC, samatrhea approved these changes

2021-10-01 09:49 UTC, samatrhea requested changes

2021-10-01 09:49 UTC, samatrhea commented on comet_sdk_test_netf.bat
> +dotnet test CDP4-SDK-NETF.sln --framework net452 --filter="(TestCategory!~WebServicesDependent) & (TestCategory!~AppVeyorExclusion)"
we can also do net48, not so interested in net452 anymore now that COMET is also on net48

2021-10-01 10:06 UTC, samatrhea approved these changes

2021-10-01 10:57 UTC, merged