[WIP] Add CDP4Reporting
RHEAGROUP/COMET-SDK-Community-Edition pull request #248
Opened 2022-11-29 13:32 UTC by lxatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-SDK-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Add CDP4Reporting

2022-12-05 10:30 UTC, samatrhea requested changes

2022-12-05 10:30 UTC, samatrhea commented on CDP4Reporting/CDP4Reporting.csproj
> +	  <Authors>Sam, Merlin, Alex, Naron, Alexander, Yevhen, Nathanael</Authors>
Please only keep Alex, Sam and Alexander for now

2022-12-05 10:30 UTC, samatrhea commented on CDP4Reporting/CDP4Reporting.csproj
> +	  <PackageTags>CDP COMET ECSS-E-TM-10-25 JSON</PackageTags>
remove JSON

2022-12-05 10:30 UTC, samatrhea commented on CDP4Reporting/DataCollection/DataCollectorCategory.cs
> +//    Author: Sam Gerené, Merlin Bieze, Alex Vorobiev, Naron Phou, Alexander van Delft, Nathanael Smiechowski
please remove all authors on all files and keep Alex, Sam and Alexander for now

2023-01-13 13:46 UTC, samatrhea requested changes
Not so sure i agree with the use of `ExcludeFromCodeCoverage`, it hides that we don't have coverage... best be honest about it and improve when we can instead of forgetting about it

some other minor comments (also from past review) that need to be fixed

2023-01-13 13:46 UTC, samatrhea commented on CDP4Reporting.Tests/CDP4Reporting.Tests.csproj
> +    <Product>CDP4BuiltInRules.Tests</Product>
please update to the correct name

2023-01-13 13:46 UTC, samatrhea commented on CDP4Reporting.Tests/DataCollection/CategoryDecompositionHierarchyTestFixture.cs
> +//    Copyright (c) 2015-2022 RHEA System S.A.
2023 (please update all over)

2023-01-13 13:46 UTC, samatrhea commented on CDP4Reporting/DataCollection/DataCollectorBooleanParameter.cs
> +    public class DataCollectorBooleanParameter<TRow> : DataCollectorParameter<TRow, bool>
docs state that this is an abstract base class, while it is not

2023-01-13 13:46 UTC, samatrhea commented on CDP4Reporting/DataCollection/DataCollectorBooleanParameter.cs
> +        [ExcludeFromCodeCoverage] // Remove attribute when more logic is added to this method. It's only SDK functionality now and that is fully covered.
please remove this `ExcludeFromCodeCoverage`

2023-01-13 13:46 UTC, samatrhea commented on CDP4Reporting/DataCollection/DataCollectorDoubleParameter.cs
> +    public class DataCollectorDoubleParameter<TRow> : DataCollectorParameter<TRow, double>
docs state that this is an abstract class while it is not

2023-01-13 13:46 UTC, samatrhea commented on CDP4Reporting/DataCollection/DataCollectorStateDependentPerRowDoubleParameter.cs
> +        [ExcludeFromCodeCoverage] // Remove attribute when more logic is added to this method. It's only SDK functionality now and that is fully covered.
please remove `ExcludeFromCodeCoverage`

2023-01-13 13:46 UTC, samatrhea commented on CDP4Reporting/DynamicTableChecker/IDynamicTableCellsCollector.cs
> +    public class DynamicTableCell
please add docs to this class, my preference would also be to put this class in its own file

2023-01-16 13:06 UTC, samatrhea approved these changes

2023-01-17 08:40 UTC, antoineatrhea approved these changes

2023-01-17 14:06 UTC, merged