[Add] RabbitMQ client and ThingsChanged Message Producer and consumer
RHEAGROUP/COMET-SDK-Community-Edition pull request #306
Opened 2024-01-31 14:57 UTC by nathanatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-SDK-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)
closes #305 
### Description

- [x] Implement the SDK part of https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues/327
   - [x]  RabbitMQ client
   - [x] ThingsChangedMessageProducer
   - [x] ThingsChangedMessageConsumer
   - [x] BackgroundThingsChangedMessageProducer
- [x] Added tests

2024-01-31 15:05 UTC, samatrhea requested changes

2024-01-31 15:05 UTC, samatrhea commented on CDP4ServicesMessaging/Services/BackgroundMessageProducers/BackgroundThingsMessageProducer.cs
> +    /// Background service for BackgroundThingsMessageProducer messages from a message queue.
please add 

```
<see cref="BackgroundThingsMessageProducer" /> 
```

2024-01-31 15:11 UTC, samatrhea commented on CDP4ServicesMessaging/Messages/ThingsChangedMessage.cs
> +        public Version ModelVersion { get; set; }
internally we should always serialize and deserialize using max version, not based on whomever sent the POST request. Which means we don't need this here

2024-02-01 09:49 UTC, antoineatrhea requested changes

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging.Tests/CDP4ServicesMessaging.Tests.csproj
> +    <Folder Include="Services\Messaging\" />
this can be removed

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging.Tests/Serializers/Json/Cdp4MessageSerializerTestFixture.cs
> +            Assert.That(newMessage.ChangedThings.Count(), Is.EqualTo(3));
Wrap those with Assert.Multiple please

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging.Tests/Services/Messaging/MessageClientServiceTestFixture.cs
> +            Assert.ThrowsAsync<TimeoutException>(() => this.Service.Connect());
Use Assert.That(() ...., Throws.Exception.TypeOf<>...)

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging.Tests/Services/Messaging/MessageClientServiceTestFixture.cs
> +            this.Model.VerifyAdd(m => m.ModelShutdown += It.IsAny<EventHandler<ShutdownEventArgs>>(), Times.Exactly(5));
Wrap everything with Assert.Multiple

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging.Tests/Services/ThingMessaging/ThingMessageConsumerTestFixture.cs
> +            Assert.DoesNotThrowAsync(() => this.Service.AddListener(x => messageReceived.Add(x)));
Same as before

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging.Tests/Services/ThingMessaging/ThingMessageConsumerTestFixture.cs
> +            Assert.ThrowsAsync<TimeoutException>(async () => (await this.Service.Listen())
Same

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging.Tests/Services/ThingMessaging/ThingMessageConsumerTestFixture.cs
> +            Assert.DoesNotThrowAsync(async () => (await this.Service.Listen())
Same

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging.Tests/Services/ThingMessaging/ThingMessageProducerTestFixture.cs
> +            this.Model.Verify(x => x.BasicPublish(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<bool>(),It.IsAny<IBasicProperties>(), It.IsAny<ReadOnlyMemory<byte>>()),
Assert.Mutliple

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging/CDP4ServicesMessaging.csproj
> +    <VersionPrefix>1.0.0</VersionPrefix>
The version should be aligned with the others

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging/CDP4ServicesMessaging.csproj
> +        <PackageReference Include="CDP4Dal-CE" Version="24.1.1" />
Use projectReference

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging/Services/Messaging/Interfaces/IMessageClientService.cs
> +}
missing EOF

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging/Services/Messaging/Interfaces/IMessageQueueClientBaseService.cs
> +}
missing EOF

2024-02-01 09:49 UTC, antoineatrhea commented on CDP4ServicesMessaging.Tests/GlobalUsings.cs
> +global using NUnit.Framework;
missing EOF

2024-02-01 10:23 UTC, antoineatrhea approved these changes

2024-02-01 10:48 UTC, samatrhea approved these changes

2024-02-01 14:31 UTC, merged